package CorbaConversion;

/**
* CorbaConversion/IConversionRemoteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Conversion.idl
* lundi 20 novembre 2023 15 h 03 GMT+01:00
*/

public final class IConversionRemoteHolder implements org.omg.CORBA.portable.Streamable
{
  public CorbaConversion.IConversionRemote value = null;

  public IConversionRemoteHolder ()
  {
  }

  public IConversionRemoteHolder (CorbaConversion.IConversionRemote initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CorbaConversion.IConversionRemoteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CorbaConversion.IConversionRemoteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CorbaConversion.IConversionRemoteHelper.type ();
  }

}
