package CorbaConversion;


/**
* CorbaConversion/IConversionRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Conversion.idl
* lundi 20 novembre 2023 15 h 03 GMT+01:00
*/

public interface IConversionRemoteOperations 
{

  //client et serveur utilise java montant est un parametre d'entrée
  double ConversionMontant (double montant);
} // interface IConversionRemoteOperations
